name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies directly
        run: |
          uv pip install fastapi uvicorn python-multipart streamlit requests \
                         sentence-transformers transformers torch faiss-cpu \
                         PyMuPDF nltk numpy pytest pytest-asyncio httpx

      - name: Cache NLTK data
        uses: actions/cache@v4
        with:
          path: ~/.local/share/nltk_data
          key: nltk-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            nltk-${{ runner.os }}-

      - name: Download NLTK data (punkt + punkt_tab)
        run: |
          uv run python -m nltk.downloader punkt punkt_tab

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
